### ISSUE TITLE
правки по ДЗ

### ISSUE THREAD

**Issue by kateryna06** [magnolia84/magnolia84.github.io#1]
1. мы верстаем дивами, а не таблицами. По этому все табличные теги нужно убрать. Табличные теги используем на стрнице тогда, когда у нас есть таблица на странице, а таковой у нас тут нет
2.  <link rel="stylesheet" href="./css/style.css"> нужно прописать правильно путь для стилей (посмотри плиз еще раз урок)
3. Все hr нужно убрать и линию задать другим способом. Если не придумаешь как пиши и я подскажу
4. Посмотри тут http://htmlbook.ru/html/img как правильно прописываются атрибуты для картинки и найду у себя ошибку 
5. Для задания цвета (box-shadow: 0 0 4px #ccc;) ты использовала сокращенную запись, было бы отлично если и для задания цвета для других стилей ты бы тоже использовала сокращенную запись. Это не ошибка, но если возможно писать сокращенно, то лучше это делать ))
6. Поудалять лишние пустые строки в css 

Если будут вопросы - пиши

**Comment by magnolia84** [comment]
@kateryna06 У меня звичайно ж є питання:
1,3. Де у Вашому завданні [тут](https://github.com/goit-fe/markup_fe2o/blob/master/lesson_01/readme.md) вказано, що не можна користуватися таблицями і тегом hr? Зацитую суть самого завдання:

> 1. Ваша верстка должна выглядеть как можно более похожей к макету, т.е. должны совпадать размеры, расположение, цвета.
> 2. Информацию (текст, фото) заменяйте на свою, так мы сможем быстрее познакомиться ;)

Очевидно, що ніде. Тож напрошуються висновки:
а) завдання складено непрофесійно. (Зразок професійно складеного завдання можна глянути, наприклад, [тут](http://www.itmathrepetitor.ru/zadachi-po-html-i-css-zadacha-1-tolko-den-ne-po/))
б) зауваження недоречні, бо не були явно вказані у завданні.
2. Шлях для стилів вказаний вірно. Інакше б браузер їх просто не відображав. [Однак це не так](http://magnolia84.github.io/GoIT/markup/home/lesson1/task1.html). Вказано вірний відносний шлях до файлу стилів через "." (поточна папка), яку можна ставити чи ні на розсуд верстальника. Тож уточніть, будь ласка, де тут помилка?
4. Виправила.
5. І скорочений, і повний запис є вірними. Тож це не може вважатися помилкою в принципі.
6. Зустрічне питання: як впливають порожні рядки на якість верстки? Здається, що ніяк. Не пригадую, щоб форматування коду у Вас взагалі розглядалося у Tech Skills і це є справою смаку.

**Comment by kateryna06** [comment]
1,3 . В задании этого не указано. Но вы же хотите научиться верстать правильно. А использование hr в верстке не семантично. Нужно писать код с меньшим количеством тегом и лишней вложенностью. 

Допустим, ты сделала проект, в котом использовала hr. Прошло какое-то время и клиент просит убрать его. Но не всегда есть доступ к html. А если эти hr встречаются не только на одной странице или не только в одном месте. У тебя займет намного больше времени, чтоб убрать ее везде в контенте, если бы ты задала эту линию в css 

Табличная верстка - это уже устаревшее и ей уже никто не пользуется (за исключением,если есть таблица на странице)  http://htmlbook.ru/content/preimushchestva-i-nedostatki-tablits
1. Я и не говорю что это ошибка. Но плюс в сокращенной записи в том, что мы сокращаем размер файла. 
2. Про форматирование файлов я писала в чате. Ваш код должен быть правильным, чистым и удобным для просмотра и редактирования. Чтоб, когда ваш код открыл другой человек, ему было наглядно проще разбираться в вашем коде. И опять же, избегая лишних строк, вы сокращаете размер ваших файлов. Это просто правило хорошего тона.

**Comment by magnolia84** [comment]
Зробила. Перевіряйте.

**Comment by kateryna06** [comment]
1. Точка в css так и осталась. Также есть точка в пути у картинки. Я понимаю, что от этого все работает, но есть стандарты, которых нужно придерживаться.
2. Нужно убрать br в контенте. Их лучше не использовать, т.к. это лишний тег в твоем коде. Если ты хочешь отступить от заголовка, то лучше добавить отступ
3. У тебя есть 3 блока для которых ты используешь одни и те же стили 
   http://joxi.ru/4DmBK5RHE4Xb2P Но при этом у них 3 разных класса. Это не правильно, если у тебя есть на странице блоки с одними и теме же стилями, то у них должен быть и один и тот же класс
4. по бокам http://joxi.ru/YxAeZwXhobYgry не хватает отступов

**Comment by magnolia84** [comment]
1. Крапка в шляхах є абсолютно правильною згідно [правил побудови відносних шляхів](http://www.webreference.com/html/tutorial2/3.html). Це і є стандарт. Тож не бачу причин це виправляти поки не буде доведено протилежне.
   
   > A directory called . (one period) refers to the current directory. 
2. Поправила.
3. Використовується лише 2 однакових блока (div), а не 3. Клас `job-title` застосовується до параграфу.
4. Поправила.

Надіюсь, що це вичерпний список недоліків і нових не з'явиться після чергової перевірки.

**Comment by kateryna06** [comment]
я вижу что 2 дива и параграф, но у тебя на них висят одни и теже стили, а классы стоят разные. Так не должно быть. Вот если бы у параграфа или дивов были б какие-нибудь дополнительные свойства, то тогда это допустимо. А так я не вижу смысла добавлять лишний класс.

**Comment by magnolia84** [comment]
@kateryna06 хотілося б дізнатись, чи є якісь ще зауваження.

Дякую.

**Comment by kateryna06** [comment]
ты вроде убирала br в head-content, а теперь он опять появился. Нужно удалить

**Comment by magnolia84** [comment]
@kateryna06 щойно видалила. СОРІ.

**Comment by kateryna06** [comment]
ЗАЧЕТ
